version: '3.3'
services:
  nginx:
    image: nginx:alpine
    networks:
      - phone-network
    # deploy:
    #   mode: replicated
    #   replicas: 1
    # placement:
    #   constraints:
    #     - node.labels.nginx == true
    ports:
      - 80:80
    tty: true

    volumes:
      - ./sites.conf:/etc/nginx/conf.d/default.conf
      - ./sites-available:/etc/nginx/sites-available

networks:
  phone-network:
    external: false
    name: phone-network
