version: '3.3'
services:
  mysql:
    image: mariadb:10.5.8
    environment:
      MYSQL_DATABASE: 'phone-market'
      MYSQL_USER: 'phone'
      MYSQL_PASSWORD: 'phone2021'
      MYSQL_ROOT_PASSWORD: 'phone2021'
    volumes:
      - './maria-db:/var/lib/mysql'
    ports:
      - '3306:3306'
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redisdb:
    container_name: redisdb
    image: redis:latest
    environment:
      REDIS_PASSWORD: '123456789'
    volumes:
      - './redis-db:/data'
    entrypoint: redis-server --appendonly yes
    ports:
      - '6379:6379'
    restart: always
